# Generated by Django 6.0.4 on 2026-08-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_villageissue_status_villageissue_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageissue',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='issues/'),
        ),
    ]
